# Generated by Django 4.1.2 on 2022-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome completo', max_length=58, verbose_name='nome')),
                ('fone', models.CharField(help_text='número de telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='endereço de email', max_length=168, unique=True, verbose_name='E-mail')),
                ('funcao', models.CharField(help_text='Função', max_length=58, verbose_name='função')),
                ('data_admissao', models.DateField(help_text='Data de admissão', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
