# Generated by Django 4.1.2 on 2022-11-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_cliente_foto'),
        ('servico', '0001_initial'),
        ('funcionario', '0002_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(help_text='Data e hora do atendimento', verbose_name='Horario')),
                ('situacao', models.CharField(choices=[('R', 'Realizado'), ('A', 'Agendado'), ('C', 'Cancelado')], default='A', help_text='Situações do atendimento', max_length=15, verbose_name='Situação')),
                ('cliente', models.ForeignKey(help_text='Nome do cliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(help_text='Nome do funcionario', on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionario')),
                ('servico', models.ForeignKey(help_text='Nome do serviço', on_delete=django.db.models.deletion.CASCADE, to='servico.servico', verbose_name='Servico')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
